name: unzip File

on:
  workflow_dispatch:

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Unzip the file
        run: unzip extract.zip -d extracted/
      - name: Upload extracted files as artifact
        uses: actions/upload-artifact@v4
        with:
          name: extracted-files
          path: extracted/
